services:
  postgres:
    image: postgres:alpine
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - .pgdata:/pgdata
