services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=password
      - ACCEPT_EULA=y
    volumes:
      - .mssqldata:/var/opt/mssql
